# Generated by Django 3.1.5 on 2021-01-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210112_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
