# Generated by Django 3.1.5 on 2021-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': (('CAN_VIEW_BOOK', 'Can View Book'),),
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
