# Generated by Django 3.1.5 on 2021-01-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210112_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('CAN_VIEW_BOOK', 'Can View Book'),)},
        ),
    ]
