# Generated by Django 3.1.5 on 2021-01-12 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20210112_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primeuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('prime_user', 'prime user')],
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
