# Generated by Django 3.1.5 on 2021-01-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210112_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primeuser',
            options={'permissions': [('prime_user', 'primeuser')]},
        ),
    ]
