# Generated by Django 3.1.5 on 2021-01-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210112_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primeuser',
            options={'permissions': [('prime_member', 'prime_member')]},
        ),
    ]
